# Generated by Django 3.0 on 2020-01-31 14:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0004_auto_20200131_1930'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comments',
            name='blog_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='blogid', to='blog.CreateBlog'),
        ),
    ]
