# Generated by Django 3.0 on 2020-01-31 14:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0005_auto_20200131_1946'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comments',
            name='blog_id',
            field=models.IntegerField(),
        ),
    ]
