# Generated by Django 3.0 on 2020-02-01 05:42

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0008_auto_20200201_0826'),
    ]

    operations = [
        migrations.AddField(
            model_name='createblog',
            name='date',
            field=models.DateTimeField(default=datetime.datetime(2020, 2, 1, 5, 42, 4, 101690, tzinfo=utc)),
        ),
    ]
